/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import javax.swing.JOptionPane;

/**
 *
 * @author FABÍOLA CÁCERES
 */
public class JDlgFrcFornecedor extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JDlgFrcFornecedor.class.getName());

    /**
     * Creates new form JDlgFrcFornecedor
     * @param parent
     * @param modal
     */
    public JDlgFrcFornecedor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Cadastro de Fornecedor");
        setLocationRelativeTo(null);
        jTxtFrcCodigo.setEnabled(false);
        jTxtFrcFantasia.setEnabled(false);
        jTxtFrcRazaoSocial.setEnabled(false);
        jFmtFrcCnpj.setEnabled(false);
        jFmtFrcTelefone.setEnabled(false);
        jTxtFrcEmail.setEnabled(false);
        jFmtFrcCep.setEnabled(false);
        jTxtFrcEndereco.setEnabled(false);
        jTxtFrcBairro.setEnabled(false);
        jTxtFrcCidade.setEnabled(false);
        jCboFrcEstado.setEnabled(false);
        jTxtFrcNumero.setEnabled(false);
        jTxtFrcContatoResponsavel.setEnabled(false);
        jFmtFrcDataCadastro.setEnabled(false);
        jChbFrcAtivo.setEnabled(false);
        jBtnFrcConfirmar.setEnabled(false);
        jBtnFrcCancelar.setEnabled(false);
        
    }
      public void habilitar(){
          
        jTxtFrcCodigo.setEnabled(true);
        jTxtFrcFantasia.setEnabled(true);
        jTxtFrcRazaoSocial.setEnabled(true);
        jFmtFrcCnpj.setEnabled(true);
        jFmtFrcTelefone.setEnabled(true);
        jTxtFrcEmail.setEnabled(true);
        jFmtFrcCep.setEnabled(true);
        jTxtFrcEndereco.setEnabled(true);
        jTxtFrcBairro.setEnabled(true);
        jTxtFrcCidade.setEnabled(true);
        jCboFrcEstado.setEnabled(true);
        jTxtFrcNumero.setEnabled(true);
        jTxtFrcContatoResponsavel.setEnabled(true);
        jFmtFrcDataCadastro.setEnabled(true);
        jChbFrcAtivo.setEnabled(true);
        jBtnFrcConfirmar.setEnabled(true);
        jBtnFrcCancelar.setEnabled(true);
        
        
         jBtnFrcIncluir.setEnabled(false);
         jBtnFrcAlterar.setEnabled(false);
         jBtnFrcExcluir.setEnabled(false);
         jBtnFrcPesquisar.setEnabled(false);
         
         
         
        
        
    }
    
    public void desabilitar(){
        
        jTxtFrcCodigo.setEnabled(false);
        jTxtFrcFantasia.setEnabled(false);
        jTxtFrcRazaoSocial.setEnabled(false);
        jFmtFrcCnpj.setEnabled(false);
        jFmtFrcTelefone.setEnabled(false);
        jTxtFrcEmail.setEnabled(false);
        jFmtFrcCep.setEnabled(false);
        jTxtFrcEndereco.setEnabled(false);
        jTxtFrcBairro.setEnabled(false);
        jTxtFrcCidade.setEnabled(false);
        jCboFrcEstado.setEnabled(false);
        jTxtFrcNumero.setEnabled(false);
        jTxtFrcContatoResponsavel.setEnabled(false);
        jFmtFrcDataCadastro.setEnabled(false);
        jChbFrcAtivo.setEnabled(false);
        jBtnFrcConfirmar.setEnabled(false);
        jBtnFrcCancelar.setEnabled(false);
         
        
         jBtnFrcIncluir.setEnabled(true);
         jBtnFrcAlterar.setEnabled(true);
         jBtnFrcExcluir.setEnabled(true);
         jBtnFrcPesquisar.setEnabled(true);
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTxtFrcCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTxtFrcFantasia = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTxtFrcRazaoSocial = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTxtFrcEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jFmtFrcCnpj = new javax.swing.JFormattedTextField();
        jFmtFrcTelefone = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jFmtFrcCep = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jTxtFrcEndereco = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTxtFrcBairro = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTxtFrcCidade = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jCboFrcEstado = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jTxtFrcNumero = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTxtFrcContatoResponsavel = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jFmtFrcDataCadastro = new javax.swing.JFormattedTextField();
        jLabel15 = new javax.swing.JLabel();
        jChbFrcAtivo = new javax.swing.JCheckBox();
        jBtnFrcExcluir = new javax.swing.JButton();
        jBtnFrcConfirmar = new javax.swing.JButton();
        jBtnFrcCancelar = new javax.swing.JButton();
        jBtnFrcPesquisar = new javax.swing.JButton();
        jBtnFrcAlterar = new javax.swing.JButton();
        jBtnFrcIncluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Código");

        jLabel2.setText("Fantasia");

        jLabel3.setText("Razão Social");

        jTxtFrcRazaoSocial.addActionListener(this::jTxtFrcRazaoSocialActionPerformed);

        jLabel4.setText("Cnpj");

        jLabel5.setText("Telefone");

        jLabel6.setText("Email");

        jLabel7.setText("Cep");

        jLabel8.setText("Endereço");

        jTxtFrcEndereco.addActionListener(this::jTxtFrcEnderecoActionPerformed);

        jLabel9.setText("Bairro");

        jLabel10.setText("Cidade");

        jLabel11.setText("Estado");

        jCboFrcEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MS", "SP", "RJ", "MG", "PR" }));

        jLabel12.setText("Número");

        jLabel13.setText("Contato Responsável");

        jLabel14.setText("Data de Cadastro");

        jLabel15.setText("Ativo");

        jBtnFrcExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir.png"))); // NOI18N
        jBtnFrcExcluir.setText("Excluir");
        jBtnFrcExcluir.addActionListener(this::jBtnFrcExcluirActionPerformed);

        jBtnFrcConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/confirmar.png"))); // NOI18N
        jBtnFrcConfirmar.setText("Confirmar");
        jBtnFrcConfirmar.addActionListener(this::jBtnFrcConfirmarActionPerformed);

        jBtnFrcCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        jBtnFrcCancelar.setText("Cancelar");
        jBtnFrcCancelar.addActionListener(this::jBtnFrcCancelarActionPerformed);

        jBtnFrcPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        jBtnFrcPesquisar.setText("Pesquisar");
        jBtnFrcPesquisar.addActionListener(this::jBtnFrcPesquisarActionPerformed);

        jBtnFrcAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar.png"))); // NOI18N
        jBtnFrcAlterar.setText("Alterar");
        jBtnFrcAlterar.addActionListener(this::jBtnFrcAlterarActionPerformed);

        jBtnFrcIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incluir.png"))); // NOI18N
        jBtnFrcIncluir.setText("Incluir");
        jBtnFrcIncluir.addActionListener(this::jBtnFrcIncluirActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTxtFrcEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtFrcBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTxtFrcCidade)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jCboFrcEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(74, 74, 74)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jTxtFrcNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTxtFrcContatoResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jFmtFrcDataCadastro))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel14)))
                .addGap(92, 92, 92)
                .addComponent(jChbFrcAtivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jFmtFrcTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jTxtFrcEmail))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jTxtFrcCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jTxtFrcFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jTxtFrcRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFmtFrcCep)
                            .addComponent(jFmtFrcCnpj))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(249, 249, 249)
                .addComponent(jLabel9)
                .addGap(127, 127, 127)
                .addComponent(jLabel10))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtnFrcIncluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnFrcAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnFrcExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnFrcConfirmar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnFrcCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnFrcPesquisar))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtFrcCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtFrcFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtFrcRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtFrcCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFmtFrcTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtFrcEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtFrcCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel8)
                        .addGap(13, 13, 13)
                        .addComponent(jTxtFrcEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtFrcBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtFrcCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jCboFrcEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtFrcNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtFrcContatoResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFmtFrcDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jChbFrcAtivo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtnFrcAlterar)
                            .addComponent(jBtnFrcExcluir)
                            .addComponent(jBtnFrcConfirmar)
                            .addComponent(jBtnFrcCancelar)
                            .addComponent(jBtnFrcPesquisar)
                            .addComponent(jBtnFrcIncluir))
                        .addGap(114, 114, 114))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnFrcExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnFrcExcluirActionPerformed
        // TODO add your handling code here:
        JOptionPane.showConfirmDialog(null, "Confirma a exclusão", "Selecione uma opção", JOptionPane.YES_NO_OPTION);
    }//GEN-LAST:event_jBtnFrcExcluirActionPerformed

    private void jBtnFrcConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnFrcConfirmarActionPerformed
        // TODO add your handling code here:
        desabilitar();
    }//GEN-LAST:event_jBtnFrcConfirmarActionPerformed

    private void jBtnFrcCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnFrcCancelarActionPerformed
        // TODO add your handling code here:
        desabilitar();
    }//GEN-LAST:event_jBtnFrcCancelarActionPerformed

    private void jBtnFrcPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnFrcPesquisarActionPerformed
        // TODO add your handling code here:
        JOptionPane.showInputDialog(null, "Entre com a chave primária");
    }//GEN-LAST:event_jBtnFrcPesquisarActionPerformed

    private void jBtnFrcAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnFrcAlterarActionPerformed
        // TODO add your handling code here:
        habilitar();
    }//GEN-LAST:event_jBtnFrcAlterarActionPerformed

    private void jTxtFrcEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtFrcEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtFrcEnderecoActionPerformed

    private void jBtnFrcIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnFrcIncluirActionPerformed
        // TODO add your handling code here:
        habilitar();

    }//GEN-LAST:event_jBtnFrcIncluirActionPerformed

    private void jTxtFrcRazaoSocialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtFrcRazaoSocialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtFrcRazaoSocialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                JDlgFrcFornecedor dialog = new JDlgFrcFornecedor(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnFrcAlterar;
    private javax.swing.JButton jBtnFrcCancelar;
    private javax.swing.JButton jBtnFrcConfirmar;
    private javax.swing.JButton jBtnFrcExcluir;
    private javax.swing.JButton jBtnFrcIncluir;
    private javax.swing.JButton jBtnFrcPesquisar;
    private javax.swing.JComboBox<String> jCboFrcEstado;
    private javax.swing.JCheckBox jChbFrcAtivo;
    private javax.swing.JFormattedTextField jFmtFrcCep;
    private javax.swing.JFormattedTextField jFmtFrcCnpj;
    private javax.swing.JFormattedTextField jFmtFrcDataCadastro;
    private javax.swing.JFormattedTextField jFmtFrcTelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTxtFrcBairro;
    private javax.swing.JTextField jTxtFrcCidade;
    private javax.swing.JTextField jTxtFrcCodigo;
    private javax.swing.JTextField jTxtFrcContatoResponsavel;
    private javax.swing.JTextField jTxtFrcEmail;
    private javax.swing.JTextField jTxtFrcEndereco;
    private javax.swing.JTextField jTxtFrcFantasia;
    private javax.swing.JTextField jTxtFrcNumero;
    private javax.swing.JTextField jTxtFrcRazaoSocial;
    // End of variables declaration//GEN-END:variables

}