/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import javax.swing.JOptionPane;

/**
 *
 * @author FABÍOLA CÁCERES
 */
public class JDlgFrcVendedor extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JDlgFrcVendedor.class.getName());

    /**
     * Creates new form JDlgFrcVendedor
     * @param parent
     * @param modal
     */
    public JDlgFrcVendedor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Cadastro de Vendedor");
        setLocationRelativeTo(null);
        jTxtFrcCodigo.setEnabled(false);
        jTxtFrcNome.setEnabled(false);
        jFmtFrcCPF.setEnabled(false);
        jFmtFrcTelefone.setEnabled(false);
        jTxtFrcEmail.setEnabled(false);
        jFmtFrcDataAdmissao.setEnabled(false);
        jFmtFrcSalario.setEnabled(false);
        jFmtFrcComissao.setEnabled(false);
        jBtnFrcConfirmar.setEnabled(false);
        jBtnFrcCancelar.setEnabled(false);
        
    }
    public void habilitar(){
          
        jTxtFrcCodigo.setEnabled(true);
        jTxtFrcNome.setEnabled(true);
        jFmtFrcCPF.setEnabled(true);
        jFmtFrcTelefone.setEnabled(true);
        jTxtFrcEmail.setEnabled(true);
        jFmtFrcDataAdmissao.setEnabled(true);
        jFmtFrcSalario.setEnabled(true);
        jFmtFrcComissao.setEnabled(true);
        jBtnFrcConfirmar.setEnabled(true);
        jBtnFrcCancelar.setEnabled(true);
        
        
         jBtnFrcIncluir.setEnabled(false);
         jBtnFrcAlterar.setEnabled(false);
         jBtnFrcExcluir.setEnabled(false);
         jBtnFrcPesquisar.setEnabled(false);
         
         
        
        
    }
    
    public void desabilitar(){
        
        jTxtFrcCodigo.setEnabled(false);
        jTxtFrcNome.setEnabled(false);
        jFmtFrcCPF.setEnabled(false);
        jFmtFrcTelefone.setEnabled(false);
        jTxtFrcEmail.setEnabled(false);
        jFmtFrcDataAdmissao.setEnabled(false);
        jFmtFrcSalario.setEnabled(false);
        jFmtFrcComissao.setEnabled(false);
        
        jBtnFrcConfirmar.setEnabled(false);
        jBtnFrcCancelar.setEnabled(false);
         
        
         jBtnFrcIncluir.setEnabled(true);
         jBtnFrcAlterar.setEnabled(true);
         jBtnFrcExcluir.setEnabled(true);
         jBtnFrcPesquisar.setEnabled(true);
         
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTxtFrcCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTxtFrcNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTxtFrcEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jFmtFrcCPF = new javax.swing.JFormattedTextField();
        jFmtFrcTelefone = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jFmtFrcDataAdmissao = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jFmtFrcSalario = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        jFmtFrcComissao = new javax.swing.JFormattedTextField();
        jBtnFrcCancelar = new javax.swing.JButton();
        jBtnFrcPesquisar = new javax.swing.JButton();
        jBtnFrcIncluir = new javax.swing.JButton();
        jBtnFrcAlterar = new javax.swing.JButton();
        jBtnFrcExcluir = new javax.swing.JButton();
        jBtnFrcConfirmar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Código");

        jLabel2.setText("Nome");

        jLabel3.setText("CPF");

        jLabel5.setText("Telefone");

        jLabel6.setText("E-mail");

        jLabel7.setText("Data Admissão");

        jLabel8.setText("Salário");

        jLabel9.setText("Comissão");

        jBtnFrcCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        jBtnFrcCancelar.setText("Cancelar");
        jBtnFrcCancelar.addActionListener(this::jBtnFrcCancelarActionPerformed);

        jBtnFrcPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        jBtnFrcPesquisar.setText("Pesquisar");
        jBtnFrcPesquisar.addActionListener(this::jBtnFrcPesquisarActionPerformed);

        jBtnFrcIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incluir.png"))); // NOI18N
        jBtnFrcIncluir.setText("Incluir");
        jBtnFrcIncluir.addActionListener(this::jBtnFrcIncluirActionPerformed);

        jBtnFrcAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar.png"))); // NOI18N
        jBtnFrcAlterar.setText("Alterar");
        jBtnFrcAlterar.addActionListener(this::jBtnFrcAlterarActionPerformed);

        jBtnFrcExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir.png"))); // NOI18N
        jBtnFrcExcluir.setText("Excluir");
        jBtnFrcExcluir.addActionListener(this::jBtnFrcExcluirActionPerformed);

        jBtnFrcConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/confirmar.png"))); // NOI18N
        jBtnFrcConfirmar.setText("Confirmar");
        jBtnFrcConfirmar.addActionListener(this::jBtnFrcConfirmarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jLabel2)
                        .addGap(116, 116, 116)
                        .addComponent(jLabel3)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(471, 471, 471)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnFrcIncluir)
                                .addGap(18, 18, 18)
                                .addComponent(jBtnFrcAlterar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnFrcExcluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnFrcConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnFrcCancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnFrcPesquisar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTxtFrcEmail)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel1)
                                                    .addComponent(jTxtFrcCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel6))
                                                .addGap(31, 31, 31)
                                                .addComponent(jTxtFrcNome, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jFmtFrcDataAdmissao, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jFmtFrcSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jFmtFrcCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel7))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel8)
                                                    .addComponent(jFmtFrcTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addComponent(jFmtFrcComissao, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtFrcCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtFrcNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtFrcCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtFrcTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtFrcEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtFrcDataAdmissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtFrcSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jFmtFrcComissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnFrcAlterar)
                    .addComponent(jBtnFrcIncluir)
                    .addComponent(jBtnFrcExcluir)
                    .addComponent(jBtnFrcConfirmar)
                    .addComponent(jBtnFrcCancelar)
                    .addComponent(jBtnFrcPesquisar))
                .addGap(62, 62, 62))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnFrcCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnFrcCancelarActionPerformed
        // TODO add your handling code here:
        desabilitar();
    }//GEN-LAST:event_jBtnFrcCancelarActionPerformed

    private void jBtnFrcPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnFrcPesquisarActionPerformed
        // TODO add your handling code here:
        JOptionPane.showInputDialog(null, "Entre com a chave primária");
    }//GEN-LAST:event_jBtnFrcPesquisarActionPerformed

    private void jBtnFrcIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnFrcIncluirActionPerformed
        // TODO add your handling code here:
        habilitar();
    }//GEN-LAST:event_jBtnFrcIncluirActionPerformed

    private void jBtnFrcAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnFrcAlterarActionPerformed
        // TODO add your handling code here:
        habilitar();
    }//GEN-LAST:event_jBtnFrcAlterarActionPerformed

    private void jBtnFrcExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnFrcExcluirActionPerformed
        // TODO add your handling code here:
        JOptionPane.showConfirmDialog(null, "Confirma a exclusão", "Selecione uma opção", JOptionPane.YES_NO_OPTION);
    }//GEN-LAST:event_jBtnFrcExcluirActionPerformed

    private void jBtnFrcConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnFrcConfirmarActionPerformed
        // TODO add your handling code here:
        desabilitar();
    }//GEN-LAST:event_jBtnFrcConfirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            JDlgFrcVendedor dialog = new JDlgFrcVendedor(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnFrcAlterar;
    private javax.swing.JButton jBtnFrcCancelar;
    private javax.swing.JButton jBtnFrcConfirmar;
    private javax.swing.JButton jBtnFrcExcluir;
    private javax.swing.JButton jBtnFrcIncluir;
    private javax.swing.JButton jBtnFrcPesquisar;
    private javax.swing.JFormattedTextField jFmtFrcCPF;
    private javax.swing.JFormattedTextField jFmtFrcComissao;
    private javax.swing.JFormattedTextField jFmtFrcDataAdmissao;
    private javax.swing.JFormattedTextField jFmtFrcSalario;
    private javax.swing.JFormattedTextField jFmtFrcTelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTxtFrcCodigo;
    private javax.swing.JTextField jTxtFrcEmail;
    private javax.swing.JTextField jTxtFrcNome;
    // End of variables declaration//GEN-END:variables
}
