/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
/**
 *
 * @author u10568413113
 */
public class JFrmFrcPrincipal extends javax.swing.JFrame {
//f
    /**
     * Creates new form JFrmFrcPrincipal
     */
    public JFrmFrcPrincipal() {
        initComponents();
        setTitle("Sistema loja de maquiagem");
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMnuFrcCadastro = new javax.swing.JMenu();
        jMnuFrcUsuarios = new javax.swing.JMenuItem();
        jMnuFrcCliente = new javax.swing.JMenuItem();
        jMnuFrcFornecedor = new javax.swing.JMenuItem();
        jMnuFrcProduto = new javax.swing.JMenuItem();
        jMnuFrcVendedor = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMnuFrcSair = new javax.swing.JMenuItem();
        jMnuFrcMovimento = new javax.swing.JMenu();
        jMnuFrcVenda = new javax.swing.JMenuItem();
        jMnuFrcCompra = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMnuFrcCadastro.setText("Cadastro");

        jMnuFrcUsuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuFrcUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuario.png"))); // NOI18N
        jMnuFrcUsuarios.setText("Usuarios");
        jMnuFrcUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuFrcUsuariosActionPerformed(evt);
            }
        });
        jMnuFrcCadastro.add(jMnuFrcUsuarios);

        jMnuFrcCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuFrcCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cliente.png"))); // NOI18N
        jMnuFrcCliente.setText("Cliente");
        jMnuFrcCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuFrcClienteActionPerformed(evt);
            }
        });
        jMnuFrcCadastro.add(jMnuFrcCliente);

        jMnuFrcFornecedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuFrcFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/WhatsApp Image 2026-04-15 at 16.17.25.jpg"))); // NOI18N
        jMnuFrcFornecedor.setText("Fornecedor");
        jMnuFrcFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuFrcFornecedorActionPerformed(evt);
            }
        });
        jMnuFrcCadastro.add(jMnuFrcFornecedor);

        jMnuFrcProduto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuFrcProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produto.png"))); // NOI18N
        jMnuFrcProduto.setText("Produto");
        jMnuFrcProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuFrcProdutoActionPerformed(evt);
            }
        });
        jMnuFrcCadastro.add(jMnuFrcProduto);

        jMnuFrcVendedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuFrcVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/image (2).png"))); // NOI18N
        jMnuFrcVendedor.setText("Vendedor");
        jMnuFrcVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuFrcVendedorActionPerformed(evt);
            }
        });
        jMnuFrcCadastro.add(jMnuFrcVendedor);
        jMnuFrcCadastro.add(jSeparator1);

        jMnuFrcSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuFrcSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/exit.png"))); // NOI18N
        jMnuFrcSair.setText("Sair");
        jMnuFrcSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuFrcSairActionPerformed(evt);
            }
        });
        jMnuFrcCadastro.add(jMnuFrcSair);

        jMenuBar1.add(jMnuFrcCadastro);

        jMnuFrcMovimento.setText("Movimento");

        jMnuFrcVenda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuFrcVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vendas (1).png"))); // NOI18N
        jMnuFrcVenda.setText("Venda");
        jMnuFrcMovimento.add(jMnuFrcVenda);

        jMnuFrcCompra.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuFrcCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Compras (1).png"))); // NOI18N
        jMnuFrcCompra.setText("Compra");
        jMnuFrcCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuFrcCompraActionPerformed(evt);
            }
        });
        jMnuFrcMovimento.add(jMnuFrcCompra);

        jMenuBar1.add(jMnuFrcMovimento);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMnuFrcUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuFrcUsuariosActionPerformed
        // TODO add your handling code here:                                      
    JDlgFrcUsuarios jDlgFrcUsuarios = new JDlgFrcUsuarios(this, true);
    jDlgFrcUsuarios.setVisible(true);
    }//GEN-LAST:event_jMnuFrcUsuariosActionPerformed

    private void jMnuFrcCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuFrcCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMnuFrcCompraActionPerformed

    private void jMnuFrcClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuFrcClienteActionPerformed
        // TODO add your handling code here:
    JDlgFrcClientes jDlgFrcClientes = new JDlgFrcClientes(this, true);
     jDlgFrcClientes.setLocationRelativeTo(null);
    jDlgFrcClientes.setVisible(true);
    }//GEN-LAST:event_jMnuFrcClienteActionPerformed

    private void jMnuFrcProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuFrcProdutoActionPerformed
        // TODO add your handling code here:                                       
    JDlgFrcProdutos jDlgProdutos = new JDlgFrcProdutos(this, true);
    jDlgProdutos.setVisible(true);
    }//GEN-LAST:event_jMnuFrcProdutoActionPerformed

    private void jMnuFrcFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuFrcFornecedorActionPerformed
        // TODO add your handling code here:
        JDlgFrcFornecedor jDlgFrcFornecedor = new JDlgFrcFornecedor(this, true);
    jDlgFrcFornecedor.setVisible(true);
    }//GEN-LAST:event_jMnuFrcFornecedorActionPerformed

    private void jMnuFrcVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuFrcVendedorActionPerformed
        // TODO add your handling code here:
        JDlgFrcVendedor jDlgFrcVendedor = new JDlgFrcVendedor(this, true);
    jDlgFrcVendedor.setVisible(true);
    }//GEN-LAST:event_jMnuFrcVendedorActionPerformed

    private void jMnuFrcSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuFrcSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMnuFrcSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmFrcPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmFrcPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmFrcPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmFrcPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new JFrmFrcPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu jMnuFrcCadastro;
    private javax.swing.JMenuItem jMnuFrcCliente;
    private javax.swing.JMenuItem jMnuFrcCompra;
    private javax.swing.JMenuItem jMnuFrcFornecedor;
    private javax.swing.JMenu jMnuFrcMovimento;
    private javax.swing.JMenuItem jMnuFrcProduto;
    private javax.swing.JMenuItem jMnuFrcSair;
    private javax.swing.JMenuItem jMnuFrcUsuarios;
    private javax.swing.JMenuItem jMnuFrcVenda;
    private javax.swing.JMenuItem jMnuFrcVendedor;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
